In [1]:
#notebook to curate the data for DATA 602 group project
#created by Zack Reeves Apr 2026

#We will generate a positive train dataset of X-ray confirmed AGN from the XMM-XXL survey
#We will generate a negative train dataset of quiescent and star forming galaxies from SDSS
#We will generate a test dataset of galaxies from SDSS

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from astropy.table import Table

In [8]:
xxl_raw_data = pd.read_csv('agndata/agn_sample_observations.csv')
xxl_raw_data

,observation_id,ra_deg,dec_deg,target_name,duration,source_id,distance,XXL_ID,RA_OPT,DEC_OPT,z,zerr,XLUM(erg/s),FULL_FLUX,SOFT_FLUX,HARD_FLUX,index
0,37980101,35.666670,-3.833333,XMM_LSS_1,15172,N_0_1,10.893783,N_0_1,35.632292,-4.011612,0.147232,0.000017,1.037040e+42,1.991000e-14,4.639000e-15,0.000000e+00,0
1,37982201,35.500005,-4.166667,XMM_LSS_22,16356,N_0_1,12.229112,N_0_1,35.632292,-4.011612,0.147232,0.000017,1.037040e+42,1.991000e-14,4.639000e-15,0.000000e+00,0
2,404960601,35.500005,-4.166667,XMM-LSS_22,11919,N_0_1,12.229112,N_0_1,35.632292,-4.011612,0.147232,0.000017,1.037040e+42,1.991000e-14,4.639000e-15,0.000000e+00,0
3,785101501,35.431958,-4.160167,XMM-LSS B,22000,N_0_1,14.964216,N_0_1,35.632292,-4.011612,0.147232,0.000017,1.037040e+42,1.991000e-14,4.639000e-15,0.000000e+00,0
4,785102001,35.658167,-4.167861,XMM-LSS B,22000,N_0_1,9.502639,N_0_1,35.632292,-4.011612,0.147232,0.000017,1.037040e+42,1.991000e-14,4.639000e-15,0.000000e+00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8753,37981001,36.833340,-3.500000,XMM_LSS_10,13683,N_9_6,4.373307,N_9_6,36.799960,-3.564796,0.317602,0.000044,2.560363e+43,9.990000e-14,2.771000e-14,5.985000e-14,131
8754,37981001,36.833340,-3.500000,XMM_LSS_10,13683,N_9_7,6.646270,N_9_7,36.740156,-3.559891,4.355304,0.001116,8.717013e+44,2.364000e-14,8.829000e-15,0.000000e+00,132
8755,37980901,36.499995,-3.500000,XMM_LSS_9,14629,N_9_7,14.850959,N_9_7,36.740156,-3.559891,4.355304,0.001116,8.717013e+44,2.364000e-14,8.829000e-15,0.000000e+00,132
8756,651770101,36.909795,-3.299583,XLSSC 003,121514,N_9_9,14.579598,N_9_9,36.882474,-3.541036,0.283384,0.000050,2.353035e+43,1.164000e-13,3.517000e-14,5.244000e-14,133
8757,37981001,36.833340,-3.500000,XMM_LSS_10,13683,N_9_9,3.840967,N_9_9,36.882474,-3.541036,0.283384,0.000050,2.353035e+43,1.164000e-13,3.517000e-14,5.244000e-14,133

In [12]:
#Sort on ascending distance (off axis angle) and keep only rows with the lowest off axis angle
xxl = xxl_raw_data.sort_values('distance', ascending=True).drop_duplicates(subset='XXL_ID', keep='first').reset_index(drop=True, inplace=False)
xxl

,observation_id,ra_deg,dec_deg,target_name,duration,source_id,distance,XXL_ID,RA_OPT,DEC_OPT,z,zerr,XLUM(erg/s),FULL_FLUX,SOFT_FLUX,HARD_FLUX,index
0,600090401,33.622035,-5.295694,PMN J0214-0518,60818,N_99_36,0.005510,N_99_36,33.622067,-5.295780,3.985437,0.000134,1.852594e+45,5.774000e-14,1.843000e-14,2.305000e-14,1576
1,742430201,31.549000,-6.193000,XLSSJ020611-061134,32200,N_159_4,0.108783,N_159_4,31.547488,-6.191999,0.919277,0.000388,1.254940e+44,5.483000e-14,1.973000e-14,0.000000e+00,2489
2,112370101,34.500000,-5.000000,SDS-1,61412,N_38_57,0.205841,N_38_57,34.497927,-4.997267,1.394844,0.000389,8.216301e+43,1.590000e-14,4.489000e-15,8.339000e-15,599
3,112681301,36.666660,-4.500000,MLS-6,40381,N_51_35,0.254209,N_51_35,36.670740,-4.501141,2.579800,0.000607,1.896013e+44,1.208000e-14,4.316000e-15,0.000000e+00,880
4,793580101,34.714500,-4.648556,XMM-LSS B,28000,N_39_20,0.322410,N_39_20,34.719197,-4.651166,0.826730,0.000127,1.581906e+43,8.555000e-15,1.496000e-15,7.640000e-15,637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2619,677610101,33.523335,-4.185000,XXLn032,124525,N_123_51,13.764467,N_123_51,33.377168,-4.008186,0.283068,0.000033,1.790533e+43,8.878000e-14,2.645000e-14,2.932000e-14,1976
2620,37980501,37.000005,-3.833333,XMM_LSS_5,17615,N_4_45,14.118546,N_4_45,37.199838,-3.709086,0.714712,0.000178,4.691120e+43,3.410000e-14,7.447000e-15,1.993000e-14,69
2621,404966201,34.166670,-6.166667,XMM-LSS_48,11909,N_73_1,14.124696,N_73_1,34.122101,-6.397821,1.224427,0.000507,4.729261e+44,1.175000e-13,3.698000e-14,2.951000e-14,1151
2622,148500201,34.836630,-2.977639,Mira,12218,N_57_52,14.394754,N_57_52,34.769494,-2.747311,1.087072,0.000510,2.240415e+44,7.020000e-14,2.021000e-14,2.951000e-14,944
2623,37982701,35.333340,-3.166667,XMM_LSS_27,18573,N_25_23,14.403622,N_25_23,35.093286,-3.164905,0.664425,0.000139,2.476452e+44,2.090000e-13,5.440000e-14,1.445000e-13,344

In [21]:
#OAA is still large for some sources, we'll place a generous cut at 10
xxl=xxl[xxl['distance']<10].reset_index(drop=True, inplace=False)
#We'll also cut on redshift z<3
xxl=xxl[xxl['z']<3].reset_index(drop=True, inplace=False)
print(len(xxl))

2190

In [22]:
xxl

,observation_id,ra_deg,dec_deg,target_name,duration,source_id,distance,XXL_ID,RA_OPT,DEC_OPT,z,zerr,XLUM(erg/s),FULL_FLUX,SOFT_FLUX,HARD_FLUX,index
0,742430201,31.549000,-6.193000,XLSSJ020611-061134,32200,N_159_4,0.108783,N_159_4,31.547488,-6.191999,0.919277,0.000388,1.254940e+44,5.483000e-14,1.973000e-14,0.000000e+00,2489
1,112370101,34.500000,-5.000000,SDS-1,61412,N_38_57,0.205841,N_38_57,34.497927,-4.997267,1.394844,0.000389,8.216301e+43,1.590000e-14,4.489000e-15,8.339000e-15,599
2,112681301,36.666660,-4.500000,MLS-6,40381,N_51_35,0.254209,N_51_35,36.670740,-4.501141,2.579800,0.000607,1.896013e+44,1.208000e-14,4.316000e-15,0.000000e+00,880
3,793580101,34.714500,-4.648556,XMM-LSS B,28000,N_39_20,0.322410,N_39_20,34.719197,-4.651166,0.826730,0.000127,1.581906e+43,8.555000e-15,1.496000e-15,7.640000e-15,637
4,677670135,32.824750,-6.165333,XXLn096,128211,N_155_23,0.368427,N_155_23,32.819231,-6.168025,1.807876,0.000421,1.009198e+44,1.205000e-14,2.869000e-15,0.000000e+00,2430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2185,677620135,31.659643,-4.534361,XXLn052,126913,N_138_7,9.980332,N_138_7,31.523869,-4.630455,2.269798,0.000199,2.179487e+44,1.733000e-14,4.458000e-15,0.000000e+00,2149
2186,677580136,38.002458,-4.500972,XXLn001,136539,N_107_45,9.983115,N_107_45,38.139911,-4.407213,1.363091,0.000673,1.472898e+43,0.000000e+00,2.978000e-15,0.000000e+00,1719
2187,37981001,36.833340,-3.500000,XMM_LSS_10,13683,N_9_27,9.986289,N_9_27,36.688088,-3.418739,1.609853,0.000861,1.601962e+44,2.368000e-14,8.612000e-15,0.000000e+00,142
2188,37982501,35.333340,-3.833333,XMM_LSS_25,14074,N_88_21,9.994112,N_88_21,35.166844,-3.838262,0.609018,0.000073,1.100701e+43,1.111000e-14,2.554000e-15,0.000000e+00,1405
2189,677590138,38.290917,-5.134111,XXLn011,134393,N_121_10,9.994431,N_121_10,38.124990,-5.119447,1.419409,0.000410,1.834275e+44,3.434000e-14,1.247000e-14,0.000000e+00,1930

In [23]:
#Save IDs and RA/Dec for SDSS query
xxl[['XXL_ID', 'RA_OPT', 'DEC_OPT']].to_csv('agndata/XXL_cutIDs.csv', index=False)

In [ ]:
#Ran a query on Casjobs to get galaxy matches based on nearest skycoord match and pull features

In [55]:
#reading in manga agn data to see format
manga = Table.read('agndata/manga_agn-v2_0_1.fits')
#writing IDs for matching to photo objects
manga[['MANGAID', 'RA', 'DEC']].write('agndata/manga_agn_ids.csv', overwrite=True)
#remove trailing whitespace from IDs
manga['MANGAID'] = [manga['MANGAID'][i].strip() for i in range(len(manga))]

In [56]:
manga

<Table length=387>
     MANGAID          RA         DEC     ... LOG_LBOL_BROAD LOG_LBOL_BROAD_ERR
      str17        float32     float32   ...    float32          float32
----------------- ---------- ----------- ... -------------- ------------------
 manga-10214-3703  122.92139   36.115776 ...          -99.0              -99.0
 manga-10216-9101 116.672745    18.73484 ...          -99.0              -99.0
manga-10222-12701  43.097507    -8.51039 ...          -99.0              -99.0
 manga-10222-6103  42.984875   -8.377049 ...      44.777576          45.897804
 manga-10223-3701  31.566603  -0.2914371 ...       45.36174          46.487267
 manga-10223-3702  33.524643 -0.27696112 ...          -99.0              -99.0
 manga-10226-6104  38.255203    0.420819 ...          -99.0              -99.0
 manga-10492-6103 122.972984   57.951893 ...          -99.0              -99.0
 manga-10493-1902  124.32737   52.029915 ...      44.839363           45.96015
              ...        ...         ... ...            ...                ...
  manga-9888-6104  238.29976    27.55575 ...          -99.0              -99.0
 manga-9889-12705  235.99878   24.998505 ...      45.204468          46.328568
  manga-9889-1902   234.8586    24.94357 ...          -99.0              -99.0
  manga-9889-3703  234.16231   25.906826 ...          -99.0              -99.0
  manga-9890-1901  232.41911   30.485918 ...      45.035957          46.158527
 manga-9891-12705  229.84799    28.31821 ...          -99.0              -99.0
 manga-9892-12702  247.81468   23.882635 ...      45.243786           46.36824
  manga-9892-3703  248.38391   24.984722 ...      45.305573          46.430588
  manga-9892-6102   247.4704   24.444016 ...       45.45723          46.583626
  manga-9892-6103  247.82812   24.712292 ...      44.906765          46.028164

In [63]:
# reading in and cleaning up positive train datasets
xxl_features = pd.read_csv('agndata/xxl_features_zreeves1.csv')
manga_features=pd.read_csv('agndata/manga_features_zreeves1.csv')

#adding column to designate AGN
xxl_features['is_AGN'] = [1]*len(xxl_features)

#adding column to designate AGN and how the AGN was detected
#this is stored in binary and converted to an integer
#0 is not AGN, 1 is radio, 2 is IR, 4 is optical, 8 is x-ray so 0100 -> 2 indicates an AGN detected in IR
#Manga AGN can have multiple detection methods, so 0101 -> 10 indicates an AGN detected in IR and X-ray
xxl_features['which_AGN'] = [8]*len(xxl_features) # 0 is not AGN, 1 is radio, 2 is IR, 4 is optical, 8 is x-ray

manga_features['is_AGN'] = [1]*len(manga_features)
which_AGN=[]
for i in range(len(manga_features)):
    manga_index = np.where(manga['MANGAID']==manga_features['MANGAID'][i])[0][0]
    sum_AGN = 1*manga['RADIO_AGN'][manga_index] + 2*manga['WISE_AGN'][manga_index] + 4*manga['BROAD_AGN'][manga_index] + 8*manga['BAT_AGN'][manga_index]
    which_AGN.append(sum_AGN)
manga_features['which_AGN'] = which_AGN

# setting catalog ID column to cleanly stack datasets
xxl_features['ext_ID'] = xxl_features['XXL_ID']
manga_features['ext_ID'] = manga_features['MANGAID']

In [64]:
xxl_features.columns

Index(['XXL_ID', 'objID', 'specObjID', 'ra', 'dec', 'distance', 'u_mag',
       'g_mag', 'r_mag', 'i_mag', 'z_mag', 'z', 'wise_cntr', 'w1mpro',
       'w2mpro', 'w3mpro', 'w4mpro', 'Flux_Ha_6562', 'Flux_Hb_4861',
       'Flux_OIII_5006', 'Flux_NII_6583', 'Flux_SII_6716', 'Flux_SII_6730',
       'Flux_OI_6300', 'Flux_OII_3726', 'Flux_NeIII_3868', 'is_AGN',
       'which_AGN', 'ext_ID'],
      dtype='object')

In [65]:
manga_features.columns

Index(['MANGAID', 'objID', 'ra', 'dec', 'distance', 'specObjID', 'u_mag',
       'g_mag', 'r_mag', 'i_mag', 'z_mag', 'z', 'wise_cntr', 'w1mpro',
       'w2mpro', 'w3mpro', 'w4mpro', 'h_alpha_flux', 'h_beta_flux',
       'oiii_5007_flux', 'nii_6584_flux', 'sii_6717_flux', 'sii_6731_flux',
       'oi_6300_flux', 'oii_3726_flux', 'neiii_3869_flux', 'is_AGN',
       'which_AGN', 'ext_ID'],
      dtype='object')

In [68]:
#computing emission line flux ratios for xxl and manga catalogs

#XXL
xxl_features['o3_hB'] = [np.log10( xxl_features['Flux_OIII_5006'][i] / xxl_features['Flux_Hb_4861'][i]) for i in range(len(xxl_features))]
xxl_features['n2_hA'] = [np.log10( xxl_features['Flux_NII_6583'][i] / xxl_features['Flux_Ha_6562'][i]) for i in range(len(xxl_features))]
xxl_features['s2_hA'] = [np.log10( (xxl_features['Flux_SII_6716'][i]+xxl_features['Flux_SII_6730'][i]) / xxl_features['Flux_Ha_6562'][i]) 
                         for i in range(len(xxl_features))]
xxl_features['o1_hA'] = [np.log10( xxl_features['Flux_OI_6300'][i] / xxl_features['Flux_Ha_6562'][i]) for i in range(len(xxl_features))]
xxl_features['o3_o2'] = [np.log10( xxl_features['Flux_OIII_5006'][i] / xxl_features['Flux_OII_3726'][i]) for i in range(len(xxl_features))]
xxl_features['ne3_o2'] = [np.log10( xxl_features['Flux_NeIII_3868'][i] / xxl_features['Flux_OII_3726'][i]) for i in range(len(xxl_features))]

#Manga
manga_features['o3_hB'] = [np.log10( manga_features['oiii_5007_flux'][i] / manga_features['h_beta_flux'][i]) for i in range(len(manga_features))]
manga_features['n2_hA'] = [np.log10( manga_features['nii_6584_flux'][i] / manga_features['h_alpha_flux'][i]) for i in range(len(manga_features))]
manga_features['s2_hA'] = [np.log10( (manga_features['sii_6717_flux'][i]+manga_features['sii_6731_flux'][i]) / manga_features['h_alpha_flux'][i]) 
                         for i in range(len(manga_features))]
manga_features['o1_hA'] = [np.log10( manga_features['oi_6300_flux'][i] / manga_features['h_alpha_flux'][i]) for i in range(len(manga_features))]
manga_features['o3_o2'] = [np.log10( manga_features['oiii_5007_flux'][i] / manga_features['oii_3726_flux'][i]) for i in range(len(manga_features))]
manga_features['ne3_o2'] = [np.log10( manga_features['neiii_3869_flux'][i] / manga_features['oii_3726_flux'][i]) for i in range(len(manga_features))]

/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:4: RuntimeWarning: divide by zero encountered in log10
  xxl_features['o3_hB'] = [np.log10( xxl_features['Flux_OIII_5006'][i] / xxl_features['Flux_Hb_4861'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:4: RuntimeWarning: divide by zero encountered in scalar divide
  xxl_features['o3_hB'] = [np.log10( xxl_features['Flux_OIII_5006'][i] / xxl_features['Flux_Hb_4861'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:4: RuntimeWarning: invalid value encountered in scalar divide
  xxl_features['o3_hB'] = [np.log10( xxl_features['Flux_OIII_5006'][i] / xxl_features['Flux_Hb_4861'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:5: RuntimeWarning: invalid value encountered in scalar divide
  xxl_features['n2_hA'] = [np.log10( xxl_features['Flux_NII_6583'][i] / xxl_features['Flux_Ha_6562'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:5: RuntimeWarning: divide by zero encountered in scalar divide
  xxl_features['n2_hA'] = [np.log10( xxl_features['Flux_NII_6583'][i] / xxl_features['Flux_Ha_6562'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:5: RuntimeWarning: divide by zero encountered in log10
  xxl_features['n2_hA'] = [np.log10( xxl_features['Flux_NII_6583'][i] / xxl_features['Flux_Ha_6562'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:6: RuntimeWarning: invalid value encountered in scalar divide
  xxl_features['s2_hA'] = [np.log10( (xxl_features['Flux_SII_6716'][i]+xxl_features['Flux_SII_6730'][i]) / xxl_features['Flux_Ha_6562'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:6: RuntimeWarning: divide by zero encountered in log10
  xxl_features['s2_hA'] = [np.log10( (xxl_features['Flux_SII_6716'][i]+xxl_features['Flux_SII_6730'][i]) / xxl_features['Flux_Ha_6562'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:6: RuntimeWarning: divide by zero encountered in scalar divide
  xxl_features['s2_hA'] = [np.log10( (xxl_features['Flux_SII_6716'][i]+xxl_features['Flux_SII_6730'][i]) / xxl_features['Flux_Ha_6562'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:8: RuntimeWarning: divide by zero encountered in log10
  xxl_features['o1_hA'] = [np.log10( xxl_features['Flux_OI_6300'][i] / xxl_features['Flux_Ha_6562'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  xxl_features['o1_hA'] = [np.log10( xxl_features['Flux_OI_6300'][i] / xxl_features['Flux_Ha_6562'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:8: RuntimeWarning: invalid value encountered in scalar divide
  xxl_features['o1_hA'] = [np.log10( xxl_features['Flux_OI_6300'][i] / xxl_features['Flux_Ha_6562'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:8: RuntimeWarning: invalid value encountered in log10
  xxl_features['o1_hA'] = [np.log10( xxl_features['Flux_OI_6300'][i] / xxl_features['Flux_Ha_6562'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:9: RuntimeWarning: divide by zero encountered in log10
  xxl_features['o3_o2'] = [np.log10( xxl_features['Flux_OIII_5006'][i] / xxl_features['Flux_OII_3726'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:9: RuntimeWarning: divide by zero encountered in scalar divide
  xxl_features['o3_o2'] = [np.log10( xxl_features['Flux_OIII_5006'][i] / xxl_features['Flux_OII_3726'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:9: RuntimeWarning: invalid value encountered in scalar divide
  xxl_features['o3_o2'] = [np.log10( xxl_features['Flux_OIII_5006'][i] / xxl_features['Flux_OII_3726'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:10: RuntimeWarning: divide by zero encountered in log10
  xxl_features['ne3_o2'] = [np.log10( xxl_features['Flux_NeIII_3868'][i] / xxl_features['Flux_OII_3726'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:10: RuntimeWarning: divide by zero encountered in scalar divide
  xxl_features['ne3_o2'] = [np.log10( xxl_features['Flux_NeIII_3868'][i] / xxl_features['Flux_OII_3726'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:10: RuntimeWarning: invalid value encountered in scalar divide
  xxl_features['ne3_o2'] = [np.log10( xxl_features['Flux_NeIII_3868'][i] / xxl_features['Flux_OII_3726'][i]) for i in range(len(xxl_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:13: RuntimeWarning: invalid value encountered in log10
  manga_features['o3_hB'] = [np.log10( manga_features['oiii_5007_flux'][i] / manga_features['h_beta_flux'][i]) for i in range(len(manga_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:14: RuntimeWarning: invalid value encountered in scalar divide
  manga_features['n2_hA'] = [np.log10( manga_features['nii_6584_flux'][i] / manga_features['h_alpha_flux'][i]) for i in range(len(manga_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:14: RuntimeWarning: invalid value encountered in log10
  manga_features['n2_hA'] = [np.log10( manga_features['nii_6584_flux'][i] / manga_features['h_alpha_flux'][i]) for i in range(len(manga_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:15: RuntimeWarning: invalid value encountered in log10
  manga_features['s2_hA'] = [np.log10( (manga_features['sii_6717_flux'][i]+manga_features['sii_6731_flux'][i]) / manga_features['h_alpha_flux'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:15: RuntimeWarning: divide by zero encountered in log10
  manga_features['s2_hA'] = [np.log10( (manga_features['sii_6717_flux'][i]+manga_features['sii_6731_flux'][i]) / manga_features['h_alpha_flux'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:15: RuntimeWarning: divide by zero encountered in scalar divide
  manga_features['s2_hA'] = [np.log10( (manga_features['sii_6717_flux'][i]+manga_features['sii_6731_flux'][i]) / manga_features['h_alpha_flux'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:15: RuntimeWarning: invalid value encountered in scalar divide
  manga_features['s2_hA'] = [np.log10( (manga_features['sii_6717_flux'][i]+manga_features['sii_6731_flux'][i]) / manga_features['h_alpha_flux'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:17: RuntimeWarning: invalid value encountered in log10
  manga_features['o1_hA'] = [np.log10( manga_features['oi_6300_flux'][i] / manga_features['h_alpha_flux'][i]) for i in range(len(manga_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:17: RuntimeWarning: divide by zero encountered in scalar divide
  manga_features['o1_hA'] = [np.log10( manga_features['oi_6300_flux'][i] / manga_features['h_alpha_flux'][i]) for i in range(len(manga_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:17: RuntimeWarning: divide by zero encountered in log10
  manga_features['o1_hA'] = [np.log10( manga_features['oi_6300_flux'][i] / manga_features['h_alpha_flux'][i]) for i in range(len(manga_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:18: RuntimeWarning: divide by zero encountered in scalar divide
  manga_features['o3_o2'] = [np.log10( manga_features['oiii_5007_flux'][i] / manga_features['oii_3726_flux'][i]) for i in range(len(manga_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:18: RuntimeWarning: invalid value encountered in log10
  manga_features['o3_o2'] = [np.log10( manga_features['oiii_5007_flux'][i] / manga_features['oii_3726_flux'][i]) for i in range(len(manga_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:19: RuntimeWarning: divide by zero encountered in scalar divide
  manga_features['ne3_o2'] = [np.log10( manga_features['neiii_3869_flux'][i] / manga_features['oii_3726_flux'][i]) for i in range(len(manga_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:19: RuntimeWarning: invalid value encountered in log10
  manga_features['ne3_o2'] = [np.log10( manga_features['neiii_3869_flux'][i] / manga_features['oii_3726_flux'][i]) for i in range(len(manga_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2512873112.py:19: RuntimeWarning: divide by zero encountered in log10
  manga_features['ne3_o2'] = [np.log10( manga_features['neiii_3869_flux'][i] / manga_features['oii_3726_flux'][i]) for i in range(len(manga_features))]

In [73]:
# reading in and cleaning up negative data
neg_features = pd.read_csv('agndata/negative_features_zreeves1.csv')

#designate not AGN
neg_features['is_AGN'] = [0]*len(neg_features)
neg_features['which_AGN'] = [0]*len(neg_features)

neg_features['ext_ID'] = neg_features['sample_type']

#Computing emission line flux ratios
neg_features['o3_hB'] = [np.log10( neg_features['oiii_5007_flux'][i] / neg_features['h_beta_flux'][i]) for i in range(len(neg_features))]
neg_features['n2_hA'] = [np.log10( neg_features['nii_6584_flux'][i] / neg_features['h_alpha_flux'][i]) for i in range(len(neg_features))]
neg_features['s2_hA'] = [np.log10( (neg_features['sii_6717_flux'][i]+neg_features['sii_6731_flux'][i]) / neg_features['h_alpha_flux'][i]) 
                         for i in range(len(neg_features))]
neg_features['o1_hA'] = [np.log10( neg_features['oi_6300_flux'][i] / neg_features['h_alpha_flux'][i]) for i in range(len(neg_features))]
neg_features['o3_o2'] = [np.log10( neg_features['oiii_5007_flux'][i] / neg_features['oii_3726_flux'][i]) for i in range(len(neg_features))]
neg_features['ne3_o2'] = [np.log10( neg_features['neiii_3869_flux'][i] / neg_features['oii_3726_flux'][i]) for i in range(len(neg_features))]

/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/4195318836.py:13: RuntimeWarning: invalid value encountered in log10
  neg_features['s2_hA'] = [np.log10( (neg_features['sii_6717_flux'][i]+neg_features['sii_6731_flux'][i]) / neg_features['h_alpha_flux'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/4195318836.py:13: RuntimeWarning: divide by zero encountered in log10
  neg_features['s2_hA'] = [np.log10( (neg_features['sii_6717_flux'][i]+neg_features['sii_6731_flux'][i]) / neg_features['h_alpha_flux'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/4195318836.py:15: RuntimeWarning: invalid value encountered in log10
  neg_features['o1_hA'] = [np.log10( neg_features['oi_6300_flux'][i] / neg_features['h_alpha_flux'][i]) for i in range(len(neg_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/4195318836.py:15: RuntimeWarning: divide by zero encountered in log10
  neg_features['o1_hA'] = [np.log10( neg_features['oi_6300_flux'][i] / neg_features['h_alpha_flux'][i]) for i in range(len(neg_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/4195318836.py:16: RuntimeWarning: divide by zero encountered in scalar divide
  neg_features['o3_o2'] = [np.log10( neg_features['oiii_5007_flux'][i] / neg_features['oii_3726_flux'][i]) for i in range(len(neg_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/4195318836.py:16: RuntimeWarning: invalid value encountered in log10
  neg_features['o3_o2'] = [np.log10( neg_features['oiii_5007_flux'][i] / neg_features['oii_3726_flux'][i]) for i in range(len(neg_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/4195318836.py:17: RuntimeWarning: divide by zero encountered in scalar divide
  neg_features['ne3_o2'] = [np.log10( neg_features['neiii_3869_flux'][i] / neg_features['oii_3726_flux'][i]) for i in range(len(neg_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/4195318836.py:17: RuntimeWarning: invalid value encountered in log10
  neg_features['ne3_o2'] = [np.log10( neg_features['neiii_3869_flux'][i] / neg_features['oii_3726_flux'][i]) for i in range(len(neg_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/4195318836.py:17: RuntimeWarning: divide by zero encountered in log10
  neg_features['ne3_o2'] = [np.log10( neg_features['neiii_3869_flux'][i] / neg_features['oii_3726_flux'][i]) for i in range(len(neg_features))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/4195318836.py:17: RuntimeWarning: invalid value encountered in scalar divide
  neg_features['ne3_o2'] = [np.log10( neg_features['neiii_3869_flux'][i] / neg_features['oii_3726_flux'][i]) for i in range(len(neg_features))]

In [74]:
neg_features.columns

Index(['specObjID', 'objID', 'z', 'survey', 'specsfr_tot_p50', 'sfr_tot_p50',
       'lgm_tot_p50', 'sample_type', 'u_mag', 'g_mag', 'r_mag', 'i_mag',
       'z_mag', 'Column1', 'wise_cntr', 'w1mpro', 'w2mpro', 'w3mpro', 'w4mpro',
       'h_alpha_flux', 'h_beta_flux', 'oiii_5007_flux', 'nii_6584_flux',
       'sii_6717_flux', 'sii_6731_flux', 'oi_6300_flux', 'oii_3726_flux',
       'neiii_3869_flux', 'is_AGN', 'which_AGN', 'ext_ID', 'o3_hB', 'n2_hA',
       's2_hA', 'o1_hA', 'o3_o2', 'ne3_o2'],
      dtype='object')

In [76]:
#stacking data

#desginating the columns we want
columns = ['ext_ID', 'objID', 'specObjID', 'z', 
           'u_mag', 'g_mag', 'r_mag', 'i_mag', 'z_mag',  #SDSS color magnitudes
           'w1mpro', 'w2mpro', 'w3mpro', 'w4mpro',       #WISE color magnitudes
           'o3_hB', 'n2_hA', 's2_hA', 'o1_hA', 'o3_o2', 'ne3_o2',  #emission flux ratios
           'is_AGN', 'which_AGN']                        #AGN indicator

train_dataset = pd.concat([xxl_features[columns], manga_features[columns], neg_features[columns]], axis=0).reset_index(drop=True, inplace=False)

In [78]:
#computing SDSS and WISE colors

#SDSS
train_dataset['u-g'] = [train_dataset['u_mag'][i] - train_dataset['g_mag'][i] for i in range(len(train_dataset))]
train_dataset['u-r'] = [train_dataset['u_mag'][i] - train_dataset['r_mag'][i] for i in range(len(train_dataset))]
train_dataset['u-i'] = [train_dataset['u_mag'][i] - train_dataset['i_mag'][i] for i in range(len(train_dataset))]
train_dataset['u-z'] = [train_dataset['u_mag'][i] - train_dataset['z_mag'][i] for i in range(len(train_dataset))]
train_dataset['g-r'] = [train_dataset['g_mag'][i] - train_dataset['r_mag'][i] for i in range(len(train_dataset))]
train_dataset['g-i'] = [train_dataset['g_mag'][i] - train_dataset['i_mag'][i] for i in range(len(train_dataset))]
train_dataset['g-z'] = [train_dataset['g_mag'][i] - train_dataset['z_mag'][i] for i in range(len(train_dataset))]
train_dataset['r-i'] = [train_dataset['r_mag'][i] - train_dataset['i_mag'][i] for i in range(len(train_dataset))]
train_dataset['r-z'] = [train_dataset['r_mag'][i] - train_dataset['z_mag'][i] for i in range(len(train_dataset))]
train_dataset['i-z'] = [train_dataset['i_mag'][i] - train_dataset['z_mag'][i] for i in range(len(train_dataset))]

#WISE
train_dataset['w1-w2'] = [train_dataset['w1mpro'][i] - train_dataset['w2mpro'][i] for i in range(len(train_dataset))]
train_dataset['w1-w3'] = [train_dataset['w1mpro'][i] - train_dataset['w3mpro'][i] for i in range(len(train_dataset))]
train_dataset['w1-w4'] = [train_dataset['w1mpro'][i] - train_dataset['w4mpro'][i] for i in range(len(train_dataset))]
train_dataset['w2-w3'] = [train_dataset['w2mpro'][i] - train_dataset['w3mpro'][i] for i in range(len(train_dataset))]
train_dataset['w2-w4'] = [train_dataset['w2mpro'][i] - train_dataset['w4mpro'][i] for i in range(len(train_dataset))]
train_dataset['w3-w4'] = [train_dataset['w3mpro'][i] - train_dataset['w4mpro'][i] for i in range(len(train_dataset))]

In [79]:
train_dataset

,ext_ID,objID,specObjID,z,u_mag,g_mag,r_mag,i_mag,z_mag,w1mpro,...,g-z,r-i,r-z,i-z,w1-w2,w1-w3,w1-w4,w2-w3,w2-w4,w3-w4
0,N_17_36,1237678888525824072,4.891026e+18,0.108212,18.90512,17.17459,16.29803,15.90310,15.57950,13.205,...,1.59509,0.39493,0.71853,0.32360,0.184,2.098,4.628,1.914,4.444,2.530
1,N_16_5,1237678888525562072,4.891043e+18,0.287298,20.92362,19.23653,17.77361,17.21519,16.87830,14.348,...,2.35823,0.55842,0.89531,0.33689,0.261,1.510,4.866,1.249,4.605,3.356
2,N_10_37,1237679255745790159,4.892067e+18,2.617279,20.75518,20.07779,20.11126,20.04045,19.70411,17.389,...,0.37368,0.07081,0.40715,0.33634,0.856,4.445,8.255,3.589,7.399,3.810
3,N_15_26,1237678879962497281,4.892074e+18,2.272744,21.07071,20.41719,20.32949,20.38523,20.00075,17.419,...,0.41644,-0.05574,0.32874,0.38448,0.787,4.932,8.559,4.145,7.772,3.627
4,N_10_33,1237679255745790329,4.892079e+18,0.636867,23.34155,21.70927,20.76383,19.45248,19.20684,15.165,...,2.50243,1.31135,1.55699,0.24564,0.683,4.505,7.126,3.822,6.443,2.621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5133,quiescent,1237668589185531975,2.922874e+18,0.088762,20.00510,18.40944,17.53162,17.10948,16.76212,14.641,...,1.64732,0.42214,0.76950,0.34736,0.013,2.507,6.128,2.494,6.115,3.621
5134,quiescent,1237668624084304041,2.921775e+18,0.256821,20.88408,19.06704,17.75558,17.19907,16.90928,14.281,...,2.15776,0.55651,0.84630,0.28979,0.387,2.563,5.502,2.176,5.115,2.939
5135,quiescent,1237671123222856013,2.898072e+18,0.125836,20.00054,18.43656,17.48127,17.00360,16.68959,13.783,...,1.74697,0.47767,0.79168,0.31401,0.176,1.869,5.097,1.693,4.921,3.228
5136,star forming,1237671124831437155,2.895955e+18,0.115627,19.70897,18.29311,17.53152,17.13425,16.84346,14.579,...,1.44965,0.39727,0.68806,0.29079,0.270,3.057,5.820,2.787,5.550,2.763
5137,star forming,1237678437016862913,7.961042e+17,0.131196,19.71690,18.75166,18.33460,18.07226,17.99157,15.803,...,0.76009,0.26234,0.34303,0.08069,0.378,3.483,6.548,3.105,6.170,3.065

In [80]:
train_dataset.to_csv('train_dataset.csv')

In [82]:
#reading in and cleaning up the test dataset
test_dataset = pd.read_csv('agndata/test_features_zreeves1.csv')

#Computing emission line flux ratios
test_dataset['o3_hB'] = [np.log10( test_dataset['oiii_5007_flux'][i] / test_dataset['h_beta_flux'][i]) for i in range(len(test_dataset))]
test_dataset['n2_hA'] = [np.log10( test_dataset['nii_6584_flux'][i] / test_dataset['h_alpha_flux'][i]) for i in range(len(test_dataset))]
test_dataset['s2_hA'] = [np.log10( (test_dataset['sii_6717_flux'][i]+test_dataset['sii_6731_flux'][i]) / test_dataset['h_alpha_flux'][i]) 
                         for i in range(len(test_dataset))]
test_dataset['o1_hA'] = [np.log10( test_dataset['oi_6300_flux'][i] / test_dataset['h_alpha_flux'][i]) for i in range(len(test_dataset))]
test_dataset['o3_o2'] = [np.log10( test_dataset['oiii_5007_flux'][i] / test_dataset['oii_3726_flux'][i]) for i in range(len(test_dataset))]
test_dataset['ne3_o2'] = [np.log10( test_dataset['neiii_3869_flux'][i] / test_dataset['oii_3726_flux'][i]) for i in range(len(test_dataset))]

#computing SDSS and WISE colors

#SDSS
test_dataset['u-g'] = [test_dataset['u_mag'][i] - test_dataset['g_mag'][i] for i in range(len(test_dataset))]
test_dataset['u-r'] = [test_dataset['u_mag'][i] - test_dataset['r_mag'][i] for i in range(len(test_dataset))]
test_dataset['u-i'] = [test_dataset['u_mag'][i] - test_dataset['i_mag'][i] for i in range(len(test_dataset))]
test_dataset['u-z'] = [test_dataset['u_mag'][i] - test_dataset['z_mag'][i] for i in range(len(test_dataset))]
test_dataset['g-r'] = [test_dataset['g_mag'][i] - test_dataset['r_mag'][i] for i in range(len(test_dataset))]
test_dataset['g-i'] = [test_dataset['g_mag'][i] - test_dataset['i_mag'][i] for i in range(len(test_dataset))]
test_dataset['g-z'] = [test_dataset['g_mag'][i] - test_dataset['z_mag'][i] for i in range(len(test_dataset))]
test_dataset['r-i'] = [test_dataset['r_mag'][i] - test_dataset['i_mag'][i] for i in range(len(test_dataset))]
test_dataset['r-z'] = [test_dataset['r_mag'][i] - test_dataset['z_mag'][i] for i in range(len(test_dataset))]
test_dataset['i-z'] = [test_dataset['i_mag'][i] - test_dataset['z_mag'][i] for i in range(len(test_dataset))]

#WISE
test_dataset['w1-w2'] = [test_dataset['w1mpro'][i] - test_dataset['w2mpro'][i] for i in range(len(test_dataset))]
test_dataset['w1-w3'] = [test_dataset['w1mpro'][i] - test_dataset['w3mpro'][i] for i in range(len(test_dataset))]
test_dataset['w1-w4'] = [test_dataset['w1mpro'][i] - test_dataset['w4mpro'][i] for i in range(len(test_dataset))]
test_dataset['w2-w3'] = [test_dataset['w2mpro'][i] - test_dataset['w3mpro'][i] for i in range(len(test_dataset))]
test_dataset['w2-w4'] = [test_dataset['w2mpro'][i] - test_dataset['w4mpro'][i] for i in range(len(test_dataset))]
test_dataset['w3-w4'] = [test_dataset['w3mpro'][i] - test_dataset['w4mpro'][i] for i in range(len(test_dataset))]

test_dataset.to_csv('test_dataset.csv')

/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:5: RuntimeWarning: invalid value encountered in log10
  test_dataset['o3_hB'] = [np.log10( test_dataset['oiii_5007_flux'][i] / test_dataset['h_beta_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:5: RuntimeWarning: invalid value encountered in scalar divide
  test_dataset['o3_hB'] = [np.log10( test_dataset['oiii_5007_flux'][i] / test_dataset['h_beta_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:5: RuntimeWarning: divide by zero encountered in scalar divide
  test_dataset['o3_hB'] = [np.log10( test_dataset['oiii_5007_flux'][i] / test_dataset['h_beta_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:5: RuntimeWarning: divide by zero encountered in log10
  test_dataset['o3_hB'] = [np.log10( test_dataset['oiii_5007_flux'][i] / test_dataset['h_beta_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:6: RuntimeWarning: invalid value encountered in log10
  test_dataset['n2_hA'] = [np.log10( test_dataset['nii_6584_flux'][i] / test_dataset['h_alpha_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:6: RuntimeWarning: invalid value encountered in scalar divide
  test_dataset['n2_hA'] = [np.log10( test_dataset['nii_6584_flux'][i] / test_dataset['h_alpha_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:6: RuntimeWarning: divide by zero encountered in scalar divide
  test_dataset['n2_hA'] = [np.log10( test_dataset['nii_6584_flux'][i] / test_dataset['h_alpha_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:6: RuntimeWarning: divide by zero encountered in log10
  test_dataset['n2_hA'] = [np.log10( test_dataset['nii_6584_flux'][i] / test_dataset['h_alpha_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:7: RuntimeWarning: invalid value encountered in log10
  test_dataset['s2_hA'] = [np.log10( (test_dataset['sii_6717_flux'][i]+test_dataset['sii_6731_flux'][i]) / test_dataset['h_alpha_flux'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:7: RuntimeWarning: invalid value encountered in scalar divide
  test_dataset['s2_hA'] = [np.log10( (test_dataset['sii_6717_flux'][i]+test_dataset['sii_6731_flux'][i]) / test_dataset['h_alpha_flux'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:7: RuntimeWarning: divide by zero encountered in scalar divide
  test_dataset['s2_hA'] = [np.log10( (test_dataset['sii_6717_flux'][i]+test_dataset['sii_6731_flux'][i]) / test_dataset['h_alpha_flux'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:7: RuntimeWarning: divide by zero encountered in log10
  test_dataset['s2_hA'] = [np.log10( (test_dataset['sii_6717_flux'][i]+test_dataset['sii_6731_flux'][i]) / test_dataset['h_alpha_flux'][i])
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:9: RuntimeWarning: invalid value encountered in log10
  test_dataset['o1_hA'] = [np.log10( test_dataset['oi_6300_flux'][i] / test_dataset['h_alpha_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:9: RuntimeWarning: invalid value encountered in scalar divide
  test_dataset['o1_hA'] = [np.log10( test_dataset['oi_6300_flux'][i] / test_dataset['h_alpha_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:9: RuntimeWarning: divide by zero encountered in log10
  test_dataset['o1_hA'] = [np.log10( test_dataset['oi_6300_flux'][i] / test_dataset['h_alpha_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:9: RuntimeWarning: divide by zero encountered in scalar divide
  test_dataset['o1_hA'] = [np.log10( test_dataset['oi_6300_flux'][i] / test_dataset['h_alpha_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:10: RuntimeWarning: invalid value encountered in log10
  test_dataset['o3_o2'] = [np.log10( test_dataset['oiii_5007_flux'][i] / test_dataset['oii_3726_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:10: RuntimeWarning: divide by zero encountered in scalar divide
  test_dataset['o3_o2'] = [np.log10( test_dataset['oiii_5007_flux'][i] / test_dataset['oii_3726_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:10: RuntimeWarning: invalid value encountered in scalar divide
  test_dataset['o3_o2'] = [np.log10( test_dataset['oiii_5007_flux'][i] / test_dataset['oii_3726_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:10: RuntimeWarning: divide by zero encountered in log10
  test_dataset['o3_o2'] = [np.log10( test_dataset['oiii_5007_flux'][i] / test_dataset['oii_3726_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:11: RuntimeWarning: invalid value encountered in log10
  test_dataset['ne3_o2'] = [np.log10( test_dataset['neiii_3869_flux'][i] / test_dataset['oii_3726_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:11: RuntimeWarning: divide by zero encountered in scalar divide
  test_dataset['ne3_o2'] = [np.log10( test_dataset['neiii_3869_flux'][i] / test_dataset['oii_3726_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:11: RuntimeWarning: invalid value encountered in scalar divide
  test_dataset['ne3_o2'] = [np.log10( test_dataset['neiii_3869_flux'][i] / test_dataset['oii_3726_flux'][i]) for i in range(len(test_dataset))]
/var/folders/t7/vv1pw8sd6xb5q0z3nsqxmmqm0000gn/T/ipykernel_91889/2422384789.py:11: RuntimeWarning: divide by zero encountered in log10
  test_dataset['ne3_o2'] = [np.log10( test_dataset['neiii_3869_flux'][i] / test_dataset['oii_3726_flux'][i]) for i in range(len(test_dataset))]